### ISSUE TITLE
Keyboard covers active fields

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-ios#199] opened 2020-08-17 20:36 UTC
The keyboard covers active fields and users can't see where/what they're typing. This happens after selecting an item from a dropdown; when adding a note; adding a field; and adding a section. The active field should be pushed up - above the keyboard - and be visible to the user.

**Comment by Sheeri** [comment] 2020-09-15 14:41
Closing, duplicate of #88

**Closed by Sheeri** 2020-09-15 14:41 UTC
Labels: days: 2, desirable: Production, enhancement
